version: "3"
services:
  api:
    image: node:alpine
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      NODE_ENV: development
      PORT: 4000
      JWT_SECRET: 'JWT_SECRET'
      SENDGRID_API_KEY: 'APIKEY'
      FACEBOOK_APP_ID: 'FACEBOOK'
      FACEBOOK_APP_SECRET: 'FACEBOOK'
    ports:
      - 4000:4000
    command: npm run dev
    container_name: API_EXPRESS